/**
 *@author:WangLK5
 *@Date:2019-04-11
 */

const menuList = [
  {
    title:'首页',
    key:'/',
    icon:'home'
  },
  {
    title:'通用组件',
    key:'/common',
    icon:'box-plot',
    children:[
      {
        title:'Ico(图标)',
        key:'/common/ico'
      },
      {
        title:'Button(按钮)',
        key:'/common/btn'
      },
      {
        title:'Badge(徽标)',
        key:'/common/badge'
      }
    ]
  },
  {
    title:'展示组件',
    key:'/show',
    icon:'qrcode',
    children:[
      {
        title:'carousel(轮播图)',
        key:'/show/carousel'
      },
      {
        title:'modal(模态框)',
        key:'/show/modal'
      },
      {
        title:'pagination(分页器)',
        key:'/show/pagination'
      },
      {
        title:'panel(折叠板)',
        key:'/show/panel'
      },
      {
        title:'photoLooker(图片查看器)',
        key:'/show/photolooker'
      },
      {
        title:'rate(评分器)',
        key:'/show/rate'
      },
      {
        title:'table(表格)',
        key:'/show/table'
      },
      {
        title:'tabs(选项卡)',
        key:'/show/tabs'
      }
    ]
  },
  {
    title:'效果组件',
    key:'/effect',
    icon:'trademark',
    children:[
      {
        title:'backTop(回到顶部)',
        key:'/effect/backtop'
      },
      {
        title:'loading(加载中)',
        key:'/effect/loading'
      },
      {
        title:'message(提示信息)',
        key:'/effect/message'
      },
      {
        title:'popConfirm(确认框)',
        key:'/effect/popconfirm'
      }
    ]
  }
]
export default menuList